# Generated by Django 4.2.5 on 2023-10-19 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, verbose_name="User Name")),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Last name"),
                ),
                (
                    "professions",
                    models.CharField(max_length=35, verbose_name="speciality"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_image/",
                        verbose_name="Profile-Image",
                    ),
                ),
                (
                    "profile_background",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_background/",
                        verbose_name="Profile-Background",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("arial", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscriptions",
                    models.ManyToManyField(
                        blank=True, related_name="followers", to="profiles.userprofile"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
